### ISSUE TITLE
[marquee] tag works?

### ISSUE THREAD

**Issue by durango** [ncb000gt/node-bbcode#1]
For some reason [marquee]whatever[/marquee] works even though it's no where found within your code (used npm install) any idea why?

**Comment by ncb000gt** [comment]
That's strange. I just wrote a test that use marquee in it and it didn't convert it over to <marque>text</marquee. Is that what you are seeing?

By design, it's supposed to just ignore something that is [text]stuff[/text] if it's not in the original lookup.

**Comment by durango** [comment]
Sorry about that, false alarm, my try/catch was failing (for those who didn't have bbcode installed). Sorry about that :S (close?)

**Comment by ncb000gt** [comment]
All good. Glad it's working.
