### ISSUE TITLE
Why parse needs a callback

### ISSUE THREAD

**Issue by elmigranto** [ncb000gt/node-bbcode#3]
As far as I can see library is synchronous.
So why does `parse` needs a callback? Why not just `return`?

**upd**
Well, it's actually both: `parse` returns if no callback was specified. Anyway, it's better to hear author's opinion on that.
Do you aim to make in asynchronous in future? If so, I believe you should pass `error` as first argument to callback.

**Comment by ncb000gt** [comment]
Actually, it should work as you've requested so long as you don't supply a callback.
